version: "3.8"

services:
  app:
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    command: npx nodemon index.js
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
